CREATE TABLE Customer (
	CustNo CHAR(4) UNIQUE NOT NULL,
	CustName TEXT NOT NULL,
	Address TEXT NOT NULL,
	Internal CHAR(1) NOT NULL,
	Contact VARCHAR(60) NOT NULL,
	Phone CHAR(7) NOT NULL,
	City TEXT NOT NULL,
	State CHAR(2) NOT NULL,
	Zip CHAR(5),
	CONSTRAINT customerPK PRIMARY KEY (CustNo) 
);

CREATE TABLE Facility (
	FacNo CHAR(4) UNIQUE NOT NULL,
	FacName TEXT UNIQUE NOT NULL,
	CONSTRAINT FacilityPK PRIMARY KEY (FacNo) 
);

CREATE TABLE Location (
	LocNo CHAR(4) UNIQUE NOT NULL,
	FacNo CHAR(4) NOT NULL,
	LocName TEXT NOT NULL,
	CONSTRAINT LocationPK PRIMARY KEY (LocNo),
	CONSTRAINT FacilityFK FOREIGN KEY (FacNo) REFERENCES Facility
);